### ISSUE TITLE
PythonShellError: python: can't open file 'recognition\yolo_run.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Automized** [shahzain345/puppeteer-hcaptcha-solver#1]
When installing the package and then running the example provided inside the readme

**Comment by shahzain345** [comment]
Did the package install the recognition files first?

**Comment by Automized** [comment]
Im not sure, I did npm install puppeteer-hcaptcha-solver then ran the example and this error was thrown

**Comment by shahzain345** [comment]
Umm the package should have installed the python files. Idk why It didnt so try installing the manually. Make a folder called recognition and then make two files: yolo.py and yolo_run.py then just copy and paste the code from this repo

**Comment by Automized** [comment]
Great, that worked. Thank you (Nice work on the project btw) :)

**Comment by shahzain345** [comment]
Np. Please leave a star as that helps me out alot
