### ISSUE TITLE
No mudule named 'cv2'

### ISSUE THREAD

**Issue by Itsredpro** [shahzain345/puppeteer-hcaptcha-solver#2]
![image](https://user-images.githubusercontent.com/87329611/174338420-3d85138d-965d-4854-9a51-14e6621ff041.png)
Got this error while using the template given on the github page.
I have python3 installed, using ubuntu 20.04.

**Comment by shahzain345** [comment]
You need to install `opencv-python` to make this work, heres how you install it. `pip install opencv-python`, if you still get errors please run this `pip install opencv-python scikit-image flask httpx requests pyyaml msvc-runtime`, this command will install all the required python modules needed for this to work

**Comment by Itsredpro** [comment]
Thank you, that works. But it seems like lot of captcha's are unsolvable. Ran a few tests and none worked, it outputted that it were unsolvable captcha's when using the demo template. Am i doing something wrong?

**Comment by shahzain345** [comment]
yep ik, i am working on a fix.

**Comment by Itsredpro** [comment]
Thank you! I will be waiting for your fix.
